from __future__ import annotations

from typing import Any, Dict, List, Optional

from contexta_client._types import (
    Context as ContextModel,
    Event,
    Goal,
    Preference,
    Project,
    ScoredMemory,
    TokenUsage,
    UserProfile,
)


class Context(ContextModel):
    def to_system_prompt(self, template: Optional[str] = None) -> str:
        if template:
            return self._render_template(template)
        sections: List[str] = []
        if self.user_profile:
            sections.append(f"## User Profile\nName: {self.user_profile.name}")
            if self.user_profile.traits:
                sections.append(f"Traits: {self._fmt_dict(self.user_profile.traits)}")
        if self.active_projects:
            lines = [f"- {p.name}: {p.description}" for p in self.active_projects if p.name]
            sections.append(f"## Active Projects\n" + "\n".join(lines))
        if self.preferences:
            lines = [f"- {p.category}: {p.value} (confidence: {p.confidence})" for p in self.preferences]
            sections.append(f"## Preferences\n" + "\n".join(lines))
        if self.goals:
            lines = [f"- {g.description} [{g.status}] ({g.progress:.0%})" for g in self.goals]
            sections.append(f"## Goals\n" + "\n".join(lines))
        if self.relevant_memories:
            lines = [f"- [{m.memory_type}] {m.title}: {m.content} (score: {m.score:.3f})" for m in self.relevant_memories]
            sections.append(f"## Relevant Memories\n" + "\n".join(lines))
        if self.recent_events:
            lines = [f"- {e.event_type}: {e.description}" for e in self.recent_events if e.description]
            sections.append(f"## Recent Events\n" + "\n".join(lines))
        sections.append(f"\n*Context generated by contexta (request_id: {self.request_id})*")
        return "\n\n".join(sections)

    def to_messages(self) -> List[Dict[str, str]]:
        messages: List[Dict[str, str]] = []
        prompt = self.to_system_prompt()
        if prompt:
            messages.append({"role": "system", "content": prompt})
        return messages

    def to_markdown(self) -> str:
        return self.to_system_prompt()

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump(exclude_none=True)

    @staticmethod
    def _fmt_dict(d: Dict[str, Any]) -> str:
        return ", ".join(f"{k}: {v}" for k, v in d.items())

    def _render_template(self, template: str) -> str:
        ctx = self.to_dict()
        import string
        return string.Template(template).safe_substitute(
            user_profile=str(ctx.get("user_profile", "")),
            active_projects=str(ctx.get("active_projects", [])),
            preferences=str(ctx.get("preferences", [])),
            goals=str(ctx.get("goals", [])),
            recent_events=str(ctx.get("recent_events", [])),
            relevant_memories=str(ctx.get("relevant_memories", [])),
            token_usage=str(ctx.get("token_usage", {})),
            request_id=ctx.get("request_id", ""),
        )
