from __future__ import annotations

from typing import Any

from contexta_client._types import Context as ContextModel


def _label(section: dict[str, Any]) -> str:
    for key in ("title", "name", "description", "content", "text", "value"):
        value = section.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return ""


class Context(ContextModel):
    def to_system_prompt(self, template: str | None = None) -> str:
        if template:
            return self._render_template(template)
        sections: list[str] = []
        if self.user_profile:
            sections.append("## User Profile\n" + self._fmt_dict(self.user_profile))
        for heading, items in (
            ("## Active Projects", self.active_projects),
            ("## Preferences", self.preferences),
            ("## Goals", self.goals),
            ("## Operating Rules", self.rules),
        ):
            lines = [f"- {_label(item)}" for item in items if _label(item)]
            if lines:
                sections.append(f"{heading}\n" + "\n".join(lines))
        for heading, items in (
            ("## Relevant Memories", self.relevant_memories),
            ("## Recent Events", self.recent_events),
        ):
            lines = [f"- {_label(item)}" for item in items if _label(item)]
            if lines:
                sections.append(f"{heading}\n" + "\n".join(lines))
        if self.token_usage:
            sections.append(f"## Token Usage\nTotal: {self.token_usage.total}")
        sections.append(f"\n*Context generated by contexta (request_id: {self.request_id})*")
        return "\n\n".join(sections)

    def to_messages(self) -> list[dict[str, str]]:
        messages: list[dict[str, str]] = []
        prompt = self.to_system_prompt()
        if prompt:
            messages.append({"role": "system", "content": prompt})
        return messages

    def to_markdown(self) -> str:
        return self.to_system_prompt()

    def to_dict(self) -> dict[str, Any]:
        return self.model_dump(exclude_none=True)

    @staticmethod
    def _fmt_dict(d: dict[str, Any]) -> str:
        return ", ".join(f"{k}: {v}" for k, v in d.items())

    def _render_template(self, template: str) -> str:
        ctx = self.to_dict()
        import string
        return string.Template(template).safe_substitute(
            user_profile=str(ctx.get("user_profile", "")),
            rules=str(ctx.get("rules", [])),
            active_projects=str(ctx.get("active_projects", [])),
            preferences=str(ctx.get("preferences", [])),
            goals=str(ctx.get("goals", [])),
            recent_events=str(ctx.get("recent_events", [])),
            relevant_memories=str(ctx.get("relevant_memories", [])),
            token_usage=str(ctx.get("token_usage", {})),
            request_id=ctx.get("request_id", ""),
        )
